Python入门
---------------

Python新手？让我们正确地设置您的Python环境：

.. toctree::
   :maxdepth: 2

   starting/which-python

- 正确地在您的系统上安装 Python

.. toctree::
    :maxdepth: 1

    starting/installation
    starting/install3/osx
    starting/install3/win
    starting/install3/linux
    starting/install/osx
    starting/install/win
    starting/install/linux


- 借助 Pipenv 使用虚拟环境：

.. toctree::
    :maxdepth: 2

    dev/virtualenvs


Python 开发环境
---------------------------

这部分指南关注 Python 开发环境，以及用于编写 Python 代码的可用且最实用的工具。

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv


写出优雅的Python代码
--------------------------------

这部分指南关注编写Python代码的最佳实践。

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license


Python应用的场景指南
--------------------------------

这部分指南关注基于不同场景的工具和模块推荐。

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/serialization
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/ml
   scenarios/clibs


部署优雅的Python代码
--------------------------------

这部分指南关注分享和部署您的Python代码。

.. toctree::
   :maxdepth: 2

   shipping/publishing
   shipping/packaging
   shipping/freezing


额外关注
----------------

这部分指南比较零散，先了解一些Python的背景知识，再关注下一步。

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news


--------------------------------------

贡献注意点和法律信息如下（给感兴趣的同学）：

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide
