开始吧
---------------

这部分指南关注搭建你的Python环境。

.. toctree::
   :maxdepth: 2

   starting/which-python

- 正确地安装Python

 .. toctree::
    :maxdepth: 1

    starting/installation
    starting/install/osx
    starting/install/win
    starting/install/linux



写出好的代码
------------------

这部分指南关注编写Python代码的最佳实践。

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license



场景/方案指南
--------------

这部分指南关注基于不同场景的工具和模块推荐。

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/clibs


部署好的代码
-------------------

这部分指南关注部署你的Python代码。

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


开发环境
-----------------------

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv




额外关注
----------------

这部分指南比较零散，先了解一些Python的背景知识，再关注下一步。

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news




--------------------------------------

贡献注意点和法律信息如下：

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide